# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - paths: default
  - extras: default
  - model: default
  - training: default
  - validation: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: ???

  - hydra: default

  # config for hyperparameter optimization
  - hparams_search: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: ${oc.env:LOCAL_CONFIG}


train: True
seed: null
gpu: True
resume: null

